### ISSUE TITLE
function starter activity review

### ISSUE THREAD

**Issue by Iankimble** [8-bitMeer/apquiz#3]
1. answer- correct. 
2. answer- correct
3. answer- partially correct. 
your assignment for this question was to create a custom function. 
4. answer- incorrect- answer is missing
you did not answer this question
5. answer- incorrect- answer is missing
you did not answer this question

partial credit boost
final score:
3/5

**Comment by 8-bitMeer** [comment]
is there any makeup work I can do to raise my grade
